# Generated by Django 5.2 on 2025-05-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokerprofile',
            name='specialization',
        ),
    ]
