# Generated by Django 5.2 on 2025-05-11 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_experience_user_license_number_and_more'),
        ('brokers', '0002_remove_brokerprofile_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerreview',
            name='contact_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='accounts.contactrequest'),
        ),
    ]
