# Generated by Django 5.2 on 2025-05-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_experience_user_license_number_and_more'),
        ('brokers', '0003_brokerreview_contact_request'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brokerreview',
            unique_together={('contact_request',)},
        ),
    ]
