# Generated by Django 5.2 on 2025-05-12 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contactrequest_review'),
        ('brokers', '0004_alter_brokerreview_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerreview',
            name='contact_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='br_contact_request', to='accounts.contactrequest'),
        ),
    ]
