# Generated by Django 5.2 on 2025-06-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Завершён'), ('canceled', 'Отменён')], default='pending', max_length=20),
        ),
    ]
