# Generated by Django 5.2 on 2025-06-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='is_consultation',
            field=models.BooleanField(default=False),
        ),
    ]
