# Generated by Django 5.2 on 2025-05-11 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_message_reply_to'),
        ('properties', '0007_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(blank=True, help_text='Опыт работы в годах (только для брокеров)', null=True, verbose_name='Experience'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, help_text='Номер лицензии (только для брокеров)', max_length=50, null=True, verbose_name='License Number'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_contact_requests', to='properties.property'),
        ),
    ]
