# Generated by Django 5.2 on 2025-05-12 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_experience_user_license_number_and_more'),
        ('brokers', '0004_alter_brokerreview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cr_review', to='brokers.brokerreview'),
        ),
    ]
