# Generated by Django 5.2 on 2025-05-12 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_favorite_property'),
        ('properties', '0009_propertyimage_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
