# Generated by Django 5.2 on 2025-05-12 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_favorite_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_brokers', to=settings.AUTH_USER_MODEL),
        ),
    ]
