# Generated by Django 5.2 on 2025-06-12 22:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('new_flat', 'Квартира в новостройке'), ('resale_flat', 'Квартира на вторичке'), ('commercial', 'Нежилое помещение'), ('house', 'Дом')], max_length=100, unique=True, verbose_name='Тип объекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(choices=[('building', 'Здание'), ('home', 'Дом'), ('warehouse', 'Склад'), ('city', 'Город')], default='home', max_length=50)),
            ],
            options={
                'verbose_name': 'Тип недвижимости',
                'verbose_name_plural': 'Типы недвижимости',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('rooms', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('location', models.CharField(max_length=200, verbose_name='Расположение')),
                ('address', models.TextField(verbose_name='Полный адрес')),
                ('main_image', models.ImageField(upload_to='properties/', verbose_name='Главное изображение')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('sold', 'Продано'), ('archived', 'В архиве')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Премиум')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Горячее предложение')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('floor', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Этаж')),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Всего этажей в доме')),
                ('apartment_type', models.CharField(blank=True, choices=[('studio', 'Студия'), ('apartment', 'Апартаменты'), ('regular', 'Обычная квартира')], max_length=20, null=True, verbose_name='Тип квартиры')),
                ('has_finishing', models.BooleanField(default=False, verbose_name='Отделка')),
                ('delivery_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год сдачи')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Дом сдан')),
                ('living_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Жилая площадь (м²)')),
                ('total_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Общая площадь (м²)')),
                ('metro_station', models.CharField(blank=True, max_length=100, verbose_name='Станция метро')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_properties', to='brokers.brokerprofile', verbose_name='Брокер')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_properties', to=settings.AUTH_USER_MODEL, verbose_name='Застройщик')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.propertytype', verbose_name='Тип недвижимости')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Изображение объекта',
                'verbose_name_plural': 'Изображения объектов',
                'ordering': ['order'],
            },
        ),
    ]
