# Generated by Django 5.2 on 2025-05-05 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, help_text='Название иконки из FontAwesome', max_length=50)),
            ],
            options={
                'verbose_name': 'Тип недвижимости',
                'verbose_name_plural': 'Типы недвижимости',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Площадь (м²)')),
                ('rooms', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('location', models.CharField(max_length=200, verbose_name='Расположение')),
                ('address', models.TextField(verbose_name='Полный адрес')),
                ('main_image', models.ImageField(upload_to='properties/', verbose_name='Главное изображение')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('sold', 'Продано'), ('archived', 'В архиве')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Премиум')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Горячее предложение')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_properties', to=settings.AUTH_USER_MODEL, verbose_name='Брокер')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_properties', to=settings.AUTH_USER_MODEL, verbose_name='Застройщик')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.propertytype', verbose_name='Тип недвижимости')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Изображение объекта',
                'verbose_name_plural': 'Изображения объектов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные объекты',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'property')},
            },
        ),
    ]
