# Generated by Django 5.2 on 2025-05-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(choices=[('new_flat', 'Квартира в новостройке'), ('resale_flat', 'Квартира на вторичке'), ('commercial', 'Нежилое помещение'), ('house', 'Дом')], max_length=100, unique=True, verbose_name='Тип объекта'),
        ),
    ]
