# Generated by Django 5.2 on 2025-05-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_propertytype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='apartment_type',
            field=models.CharField(blank=True, choices=[('studio', 'Студия'), ('apartment', 'Апартаменты'), ('regular', 'Обычная квартира')], max_length=20, null=True, verbose_name='Тип квартиры'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='icon',
            field=models.CharField(choices=[('building', 'Здание'), ('home', 'Дом'), ('warehouse', 'Склад'), ('city', 'Город')], default='home', max_length=50),
        ),
    ]
