# Generated by Django 5.2 on 2025-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_add_property_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='apartment_type',
            field=models.CharField(blank=True, choices=[('studio', 'Студия'), ('apartment', 'Апартаменты'), ('regular', 'Обычная квартира')], max_length=20, verbose_name='Тип квартиры'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(choices=[('new_flat', 'Квартира в новостройке'), ('resale_flat', 'Квартира на вторичке'), ('commercial', 'Нежилое помещение'), ('house', 'Дом')], max_length=100, unique=True, verbose_name='Тип объекта'),
        ),
    ]
