# Generated by Django 5.2 on 2025-05-06 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_apartment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Всего этажей в доме'),
        ),
    ]
