# Generated by Django 5.2 on 2025-05-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_total_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='delivery_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год сдачи'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_finishing',
            field=models.BooleanField(default=False, verbose_name='Отделка'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='Дом сдан'),
        ),
        migrations.AddField(
            model_name='property',
            name='living_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Жилая площадь (м²)'),
        ),
        migrations.AddField(
            model_name='property',
            name='metro_station',
            field=models.CharField(blank=True, max_length=100, verbose_name='Станция метро'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Общая площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Площадь (м²)'),
        ),
    ]
