# Generated by Django 5.2 on 2025-05-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_delivery_year_property_has_finishing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
    ]
