# Generated by Django 5.2 on 2025-05-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_property_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
