# Generated by Django 5.2 on 2025-05-11 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_remove_brokerprofile_specialization'),
        ('properties', '0007_delete_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_properties', to='brokers.brokerprofile', verbose_name='Брокер'),
        ),
    ]
