# Generated by Django 5.2 on 2025-05-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главное изображение'),
        ),
    ]
