# Generated by Django 5.2 on 2025-06-12 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('description', models.TextField(blank=True, verbose_name='Описание компании')),
                ('year_founded', models.PositiveIntegerField(verbose_name='Год основания')),
                ('projects_completed', models.PositiveIntegerField(default=0, verbose_name='Завершенных проектов')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='developer_logos/', verbose_name='Логотип')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль застройщика',
                'verbose_name_plural': 'Профили застройщиков',
                'ordering': ['company_name'],
            },
        ),
    ]
